FROM oven/bun:1.4.0-alpine

WORKDIR /app

COPY package.json bun.lock ./

COPY apps/frontend/package.json ./apps/frontend/package.json
COPY packages/db/package.json ./packages/db/package.json

RUN bun install

COPY apps/frontend ./apps/frontend
COPY packages/db ./packages/db

WORKDIR /app/apps/frontend

RUN bun run build

EXPOSE 3000

CMD [ "bun", "run", "start" ]