FROM oven/bun:1.4.0-alpine

WORKDIR /app

COPY package.json bun.lock ./

COPY apps/websocket/package.json ./apps/websocket/package.json
COPY packages/db/package.json ./packages/db/package.json

RUN bun install

COPY apps/websocket ./apps/websocket
COPY packages/db ./packages/db

WORKDIR /app/apps/websocket

EXPOSE 8080

CMD ["bun", "index.ts"]